[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python main.py"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[[services]]
serviceName = "telegram-bot"

[services.variables]
TOKEN = "7677905673:AAFYB0xbJfE3NRpTUIqz2AJqhjRg3Dr8UJE"